export default [
  {
    id: 1,
    name: "Mabel Johnson",
    role: "Manager",
    status: "Active",
    picture: require("./assets/admin-1.png"),
    teamImg: require("./assets/team1.png"),
  },
  {
    id: 2,
    name: "Damilola Fanmn",
    role: "Loan Officer",
    status: "Active",
    picture: require("./assets/Ellipse 12-2.png"),
    teamImg: require("./assets/team2.png"),
  },
  {
    id: 3,
    name: "Joel Charge",
    role: "Accountant",
    status: "Active",
    picture: require("./assets/Ellipse 12-3.png"),
    teamImg: require("./assets/team3.png"),
  },
  {
    id: 4,
    name: "Robinson Greg",
    role: "Secretary",
    status: "Active",
    picture: require("./assets/Ellipse 12-4.png"),
    teamImg: require("./assets/team1.png"),
  },
  {
    id: 5,
    name: "Lucas Scott",
    role: "CEC Member",
    status: "Active",
    picture: require("./assets/Ellipse 12-5.png"),
    teamImg: require("./assets/team2.png"),
  },
  {
    id: 6,
    name: "Regar Man",
    role: "CEC Member",
    status: "Active",
    picture: require("./assets/Ellipse 12.png"),
    teamImg: require("./assets/team3.png"),
  },
];
